### PR TITLE
LRQA-73903 | Account#RemoveUserFromAccountViaUsersAdmin | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-73093

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
Changes:

- Updated the test case name to indicate it is remove account from the user.
- Combined the Given, no need to add explanation for each step, if a general explanation no works, then we using And to separate it.

View changes [5793c7a](https://github.com/Sharryxue/liferay-portal/pull/396/commits/5793c7a145ec72670310a895787d4d62859eb7fa).

**Comment by Sharryxue** [comment]
Rebased and resend [Sharryxue/liferay-portal#396](https://github.com/Sharryxue/liferay-portal/pull/396).

**Pull request closed without merging**
