### PR TITLE
LPS-153652 Remove commas from end of text inputs | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LPS-153652

This should stop tests from failing. We can revert these changes once root cause is resolved.

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:account

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
Accounts tests are passing here, this should be good.

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed, added additional commit, view [5604718](https://github.com/Sharryxue/liferay-portal/pull/405/commits/5604718959ba78bd83b94cb86bddad0544121e9f).

**Comment by Sharryxue** [comment]
Rebase and resend [Sharryxue/liferay-portal#405](https://github.com/Sharryxue/liferay-portal/pull/405).

**Pull request closed without merging**
