### PR TITLE
master-lps-183829

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LPS-183829

7.3.x: https://github.com/Sharryxue/liferay-portal-ee/pull/243
7.2.x: https://github.com/Sharryxue/liferay-portal-ee/pull/244
7.1.x: https://github.com/Sharryxue/liferay-portal-ee/pull/245
7.1.x: https://github.com/Sharryxue/liferay-portal-ee/pull/246

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:portal-hotfix-release

**Comment by Sharryxue** [comment]
ci:help

**Comment by Sharryxue** [comment]
ci:test:portal-hotfix-release

**Comment by Sharryxue** [comment]
ci:test:portal-hotfix-release

**Comment by Sharryxue** [comment]
There are 11,669 tests triggered with the combined PQL

**Comment by Sharryxue** [comment]
ci:test:portal-hotfix-release

**Comment by Sharryxue** [comment]
Same number of tests with combine or not in the PQL.

**Comment by Sharryxue** [comment]
Will use the original query instead.

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:forward

**Comment by brianwulbern** [comment]
Nice work on this @Sharryxue :+1:

**Pull request closed without merging**
