### PR TITLE
LRQA-68813 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-68813

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just start reviewing.

**Comment by Sharryxue** [comment]
No changes needed.
Forwarded [liferay-usm/liferay-portal#165](https://github.com/liferay-usm/liferay-portal/pull/165)

**Pull request closed without merging**
