### PR TITLE
LRQA-78159 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-78159

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed. :)

**Comment by Sharryxue** [comment]
Rebase and resend, refer https://github.com/Sharryxue/liferay-portal/pull/510.

**Pull request closed without merging**
