### PR TITLE
LRQA-73951 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-73951

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
Changes
- Updated the commit message, view [8981c47](https://github.com/Sharryxue/liferay-portal/pull/371/commits/8981c47f139356456b7b643c67b4e93e1ca5d5af)

Notes
- For title `LRQA-73951 | master` , put all the related tickets in it.
- Add all tickets link in the comment 

Resend [Sharryxue/liferay-portal#371](https://github.com/Sharryxue/liferay-portal/pull/371)

**Pull request closed without merging**
