### PR TITLE
master-qa-42058

### PR DESCRIPTION
**Pull request by HarryC0204**
https://issues.liferay.com/browse/LRQA-42058

### CODE REVIEW

**Comment by HarryC0204** [comment]
ci:test

**Comment by HarryC0204** [comment]
ci:retest

**Comment by Sharryxue** [comment]
Hello @HarryC0204 
Please remember to resend the pr when you change the origin commit. Thanks
No more changes needed. :)

**Comment by Sharryxue** [comment]
Pushed to BChan.
master: [brianchandotcom#61100](https://github.com/brianchandotcom/liferay-portal/pull/61100)
7.1.x: [brianchandotcom#20895](https://github.com/brianchandotcom/liferay-portal-ee/pull/20895)

**Pull request closed without merging**
