### PR TITLE
master-qa-39644

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-39644

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Sharryxue** [comment]
No changes needed.

**Comment by Sharryxue** [comment]
Pushed to BChan.
[brianchandotcom#62889](https://github.com/brianchandotcom/liferay-portal/pull/62889)
[brianchandotcom#21607](https://github.com/brianchandotcom/liferay-portal-ee/pull/21607)

**Pull request closed without merging**
