### PR TITLE
LRQA-61823, 61804, LRQA-62279 | master

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-61823
https://issues.liferay.com/browse/LRQA-61804
https://issues.liferay.com/browse/LRQA-62279

/cc @patriciajeanperez
Backport above issue to 73x.
7.3.x: [brianchandotcom/liferay-portal-ee#31992](https://github.com/brianchandotcom/liferay-portal-ee/pull/31992)

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@Sharryxue invalid macro?

**Comment by Sharryxue** [comment]
Sorry @brianchandotcom , I'll taking care of the issue and resend the pr later.

**Comment by Sharryxue** [comment]
Resend [Sharryxue/liferay-portal#227](https://github.com/Sharryxue/liferay-portal/pull/227)

**Pull request closed without merging**
