### PR TITLE
master-qa-38666

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-38666

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Sharryxue** [comment]
No test changes needed. :)

**Comment by Sharryxue** [comment]
Pushed to BChan.
[brianchandotcom#58376](https://github.com/brianchandotcom/liferay-portal/pull/58376)

**Pull request closed without merging**
