### PR TITLE
LRQA-69055 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-69055

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
just start reviewing.

**Comment by Sharryxue** [comment]
Forward [liferay-usm/liferay-portal#177](https://github.com/liferay-usm/liferay-portal/pull/177)

Changes:
- Keep the step of adding page via json, since the root cause of the issue is add portlet via json.
- Remove the unnecessary declaration of sitename

**Pull request closed without merging**
