### PR TITLE
LRQA-75941, LRQA-75942, LRQA-75943 | master

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-75941
https://issues.liferay.com/browse/LRQA-75942
https://issues.liferay.com/browse/LRQA-75943

@patriciajeanperez @melodywu @lilylcl
Commits are only for master.

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
