### PR TITLE
LPS-163812 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LPS-163812

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test

**Comment by melodywu** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
Forwarded, refer https://github.com/Sharryxue/liferay-portal/pull/490.
View changes [663d5af...15ee083](https://github.com/Sharryxue/liferay-portal/compare/663d5af2f8291f35343264bbc8a75ec13c2e9f7d%5E...15ee083419700eed397ec7b17da3878e75dbaae3?expand=1)

**Pull request closed without merging**
