### PR TITLE
master-qa-60153

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LRQA-60153
Only submit to master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Just start reviewing :)

**Comment by chaowang-123** [comment]
ci:sf

**Comment by Sharryxue** [comment]
Hello @chaowang-123, please resend the commit.
* Please remove the origin branch and checkout a  new one.
* The ci:sf command should be ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:foward

**Comment by Sharryxue** [comment]
ci:forward

**Pull request closed without merging**
