### PR TITLE
LRQA-73287 Change password in setup in case URL login fails | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-73287

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:account

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed.

**Comment by Sharryxue** [comment]
Combine commits and resend [Sharryxue/liferay-portal#346](https://github.com/Sharryxue/liferay-portal/pull/346).

**Pull request closed without merging**
