### PR TITLE
LRQA-62939, LRQA-62938, LRQA-62946, LRQA-62945, LRQA-62947, LRQA-62576 | master

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-62939
https://issues.liferay.com/browse/LRQA-62938
https://issues.liferay.com/browse/LRQA-62946
https://issues.liferay.com/browse/LRQA-62945
https://issues.liferay.com/browse/LRQA-62947
https://issues.liferay.com/browse/LRQA-62576

/cc @patriciajeanperez
Backport above commits to 73.
[brianchandotcom/liferay-portal-ee#32268](https://github.com/brianchandotcom/liferay-portal-ee/pull/32268
)

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by Sharryxue** [comment]
Failure is caused by the commits, will close this pr and resend the commits.

**Comment by Sharryxue** [comment]
resend [Sharryxue/liferay-portal#233](https://github.com/Sharryxue/liferay-portal/pull/233)

**Pull request closed without merging**
