### PR TITLE
LRQA-68520 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-68520

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just start reviewing.

**Comment by Sharryxue** [comment]
No changes needed, will combine the changes instead of single forward.

**Comment by Sharryxue** [comment]
forwarded [liferay-usm/liferay-portal#137](https://github.com/liferay-usm/liferay-portal/pull/137)

**Pull request closed without merging**
