### PR TITLE
LRQA-73702 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-73702

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
Changes
- Only cherry-picked the commit of [cc9b3e9](https://github.com/Sharryxue/liferay-portal/pull/372/commits/cc9b3e9e04db9c47ff3956d70f31b779a1943f07)
- Nested the And into Given, view [e77076a](https://github.com/Sharryxue/liferay-portal/pull/373/commits/e77076aafb16c00a973f48e3dff6387277f5ba01)
- Use an exist macro to assign account user, view [e77076a](https://github.com/Sharryxue/liferay-portal/pull/373/commits/e77076aafb16c00a973f48e3dff6387277f5ba01)

Note
- We'd better add a test to cover the function of assign account to user via user portlet.

**Comment by Sharryxue** [comment]
Resend [Sharryxue/liferay-portal#373](https://github.com/Sharryxue/liferay-portal/pull/373)

**Pull request closed without merging**
