### PR TITLE
master-qa-46809

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-46809

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
cc /@GinsonRen

**Comment by Sharryxue** [comment]
no test changes needed. :)

**Comment by Sharryxue** [comment]
Pushed to BChan.
[brianchandotcom#68288](https://github.com/brianchandotcom/liferay-portal/pull/68288)

**Pull request closed without merging**
