### PR TITLE
LRQA-75078 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-75078

Resend of https://github.com/Sharryxue/liferay-portal/pull/401 under new ticket/test to better fit description.

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
Updated the description accordingly, view [537c42c](https://github.com/Sharryxue/liferay-portal/pull/411/commits/537c42cbdd77b79393fb7dfa9a621b0c0507cc71).

**Comment by Sharryxue** [comment]
Rebase and resend.
[Sharryxue/liferay-portal/411](https://github.com/Sharryxue/liferay-portal/pull/411)

**Pull request closed without merging**
