### PR TITLE
master-qa-59828

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LRQA-59828
Only commit to the master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Just start reviewing. :)

**Comment by Sharryxue** [comment]
Send to BChan [Sharryxue/liferay-portal#190](https://github.com/Sharryxue/liferay-portal/pull/190)

**Pull request closed without merging**
