### PR TITLE
LPS-129423 | master

### PR DESCRIPTION
**Pull request by Sharryxue**

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:upgrade

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Things need confirm before sending the pr forward.
Hello @patriciajeanperez,
- I'd [replaced](rtal/pull/264/commits/5815419ec8e59cc8f7f1697bf4757193158ce5c5) the _Smoke.viewWelcomePage();_ used in upgrade test with _AssertLocation(value1 = "${portalURL}/web/test/home");_, do you think there are any pertantial issue by doing this?
- For the test _Locale#VerifyFriendlyURLRedirectToEnableDefualtLocale_, I'd [used another localized](https://github.com/Sharryxue/liferay-portal/pull/264/commits/2939d65d17345cda9ae33f7c8db4c5931b8ad023) portlet for testing

Hello @pei-jung,
- By going over the upgrade test results in [patriciajeanperez/liferay-portal#328](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1524688524), I found the Hello World portlet still exist after [upgrading from 7310 to master](https://testray.liferay.com/zh/home/-/testray/case_results/1524689677), as well as [735 to master](https://testray.liferay.com/zh/home/-/testray/case_results/1524690017), not sure if this expected, would you please confirm it, thanks. In addition, this issue not affect other vesions like upgrade from 62*/70*/71*/72*/730 to master based on the upgrade results on testray.

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:test:upgrade

**Comment by patriciajeanperez** [comment]
@Sharryxue, from Pei:

> so my guess is starting 7.3, it no longer uses the widget and simply displays an image the on page. that's why it still displays after the upgrade.

> the one that displays a warning message is probably for portal versions before 7.3, which still uses the Hello World widget. That's why when we remove the portlet, it shows the warning message that the portlet is not available.

**Comment by Sharryxue** [comment]
- The [PortalSmoke#Smoke](https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/469624//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PortalSmoke_Smoke_) can be passed on local, should be flaky.
- Updated the location from _${portalURL}/web/test/home_ to _${portalURL}/web/guest/home_

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:upgrade

**Comment by Sharryxue** [comment]
ci:test:bundle

**Comment by Sharryxue** [comment]
The semantic-versioning-jdk8/0 probably fixed by [commit](https://github.com/liferay/liferay-portal/commit/34da9370183252897af2603d6edfadcb4b61f4b7)
Need keep investigating the issue in [lpkg-base-jdk8/0](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/459453/) with the bundle on local, seems the hello.velocity not started up. The hello velocity not bundled in slim bundle, that's probably why it failed on lpkg-base-jdk8/0 batch.

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
No related failure found, will try to forward the commits in a new pr [Sharryxue/liferay-portal#266]( https://github.com/Sharryxue/liferay-portal/pull/266)

**Pull request closed without merging**
