### PR TITLE
LPS-150625 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LPS-150625

### CODE REVIEW

**Comment by epark18** [comment]
Running tests here https://github.com/epark18/liferay-portal/pull/10 as well.

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
Since the component is added based on the testray result, no additional changes needed.

**Comment by Sharryxue** [comment]
Resend [Sharryxue/liferay-portal#378](https://github.com/Sharryxue/liferay-portal/pull/378)

**Pull request closed without merging**
