### PR TITLE
LPS-170777 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-170777

Commit is only for master, thanks.
/cc @lilylcl @melodywu @patriciajeanperez

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed. :)

**Comment by Sharryxue** [comment]
ci:forward

**Pull request closed without merging**
