### PR TITLE
LPS-169096 | master

### PR DESCRIPTION
**Pull request by lilylcl**
https://issues.liferay.com/browse/LPS-169096

### CODE REVIEW

**Comment by lilylcl** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Review by Sharryxue — CHANGES_REQUESTED** [review]
Hello @lilylcl,
Please make the change you made here not affect other tests, if it is necessary to update the locator, could you please confirm if it would be better to update the original one. Thanks in advance.

**Comment by lilylcl** [comment]
Hi @Sharryxue,
I change the path to IFrame#MODAL_ANY, so I don't need to modify the path. besides, the ApplicationsMenuHelper.openWorkspace macro is only used in this one case, the changes of macro won't affect other cases. Thanks!

**Comment by lilylcl** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed. :)
Rebase and resend, refer https://github.com/Sharryxue/liferay-portal/pull/524.

**Pull request closed without merging**
