### PR TITLE
LRQA-62278, LRQA-62287 | master

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-62278
https://issues.liferay.com/browse/LRQA-62287 

/cc @patriciajeanperez
Backported above issue to 73x.
7.3.x: [brianchandotcom/liferay-portal-ee/pull/32029](https://github.com/brianchandotcom/liferay-portal-ee/pull/32029)

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@Sharryxue somehow this never made it to my pull queue, but the 7.3.x did https://github.com/brianchandotcom/liferay-portal-ee/pull/32029

So I merged this one in manually.

**Comment by Sharryxue** [comment]
Thanks for merging the commits @brianchandotcom, I will close this pr then.

**Pull request closed without merging**
