### PR TITLE
master-qa-42868

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-42868

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:relevant

**Comment by suilin** [comment]
ci:reopen

**Comment by Sharryxue** [comment]
Hello @suilin,
I've updated the commit message, and add a new macro to edit the password policy syntax checking, for more detail, you can refer to the comment in the origin ticket. Thanks

**Comment by Sharryxue** [comment]
Pushed to BChan.
master: [brianchandotcom#62750](https://github.com/brianchandotcom/liferay-portal/pull/62750)
7.1.x: [brianchandotcom#21570](https://github.com/brianchandotcom/liferay-portal-ee/pull/21570)
7.0.x: [brianchandotcom#21571](https://github.com/brianchandotcom/liferay-portal-ee/pull/21571)

**Pull request closed without merging**
