### PR TITLE
LRQA-72390 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-72930

/cc @melodywu
This is only for master, thanks.

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just start reviewing.

**Comment by Sharryxue** [comment]
No changes needed. Thanks @epark18.

**Comment by Sharryxue** [comment]
ci:forward

**Pull request closed without merging**
