### PR TITLE
LRQA-60469, LRQA-60366 | master

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-60469
https://issues.liferay.com/browse/LRQA-60366

/cc @patriciajeanperez

Commits are only for master, thanks.

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:test:accounts

**Comment by Sharryxue** [comment]
Will fix the related failure in LRQA-60695.

**Pull request closed without merging**
