### PR TITLE
LRQA-74202 Fix test with steps to navigate to appropriate account

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-74202

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed.

**Comment by Sharryxue** [comment]
Resend [Sharryxue/liferay-portal#378](https://github.com/Sharryxue/liferay-portal/pull/378)

**Pull request closed without merging**
