### PR TITLE
master-qa-46862

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-46862

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
No test changes needed. :)

**Comment by Sharryxue** [comment]
Pushed to BChan.
[brianchandotcom/liferay-portal/#68445](https://github.com/brianchandotcom/liferay-portal/pull/68445)

**Pull request closed without merging**
