### PR TITLE
LPS-169786 | master

### PR DESCRIPTION
**Pull request by lilylcl**
https://issues.liferay.com/browse/LPS-169786

Commit is only for master. Thanks.

/cc @lilylcl @patriciajeanperez

### CODE REVIEW

**Comment by lilylcl** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed.

**Comment by Sharryxue** [comment]
ci:forward

**Pull request closed without merging**
