### PR TITLE
LRQA-71558 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-71558

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed.

**Comment by Sharryxue** [comment]
Combine commits and resend [Sharryxue/liferay-portal#346](https://github.com/Sharryxue/liferay-portal/pull/346).

**Pull request closed without merging**
