### PR TITLE
LPS-158349 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LPS-158349
This is a temporary fix for this ticket. At the moment, the InstanceSettings tests that deal with factory configurations are causing failures in many other tests that run in the same batch due to a bad cleanup. Having them run on separate instances allows for our tests within the InstanceSettings testcase to pass.

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:usm

**Comment by epark18** [comment]
Results look good

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
Thanks for coming up with a quick solution @epark18.
Since this is a workaround for the issue addressed in LPS-158349. We'd better file a new LRQA ticket to send the commit. And please also file a new LRQA to revert the changes, thanks in advance.

**Comment by epark18** [comment]
See https://github.com/Sharryxue/liferay-portal/pull/461

**Pull request closed without merging**
