### PR TITLE
master-qa-40642

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-40642

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Sharryxue** [comment]
No test changes needed. :)

**Comment by Sharryxue** [comment]
Pushed to BChan.
[brianchandotcom#59343](https://github.com/brianchandotcom/liferay-portal/pull/59343)

**Pull request closed without merging**
