### PR TITLE
master-qa-46804

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-46804

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by Songyuewen** [comment]
cc /@GinsonRen

**Comment by Sharryxue** [comment]
no test changes needed. :)

**Comment by Sharryxue** [comment]
Pushed to BChan.
[brianchandotcom#68288](https://github.com/brianchandotcom/liferay-portal/pull/68288)

**Pull request closed without merging**
