### PR TITLE
master-qa-50759

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/LRQA-50759
Submit for master.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed.

**Comment by Sharryxue** [comment]
Resend [Sharryxue/liferay-portal#378](https://github.com/Sharryxue/liferay-portal/pull/378)

**Pull request closed without merging**
