### PR TITLE
LRQA-75770 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-75770

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed. : )

**Comment by Sharryxue** [comment]
Rebase and resend,
https://github.com/Sharryxue/liferay-portal/pull/441

**Comment by Sharryxue** [comment]
Reopen to test sf command.

**Comment by Sharryxue** [comment]
ci:test:sf

**Pull request closed without merging**
