### PR TITLE
master-qa-42088

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-42088

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Sharryxue** [comment]
Hello @Songyuewen 
 - Make sure the display style is cards, before using icon related locator
 - No black space between the steps that are un-ordered
 - Resent the PR when you update the origin changes

**Comment by Sharryxue** [comment]
Pushed to BChan.
[brianchandotcom#61481](https://github.com/brianchandotcom/liferay-portal/pull/61481)
[brianchandotcom#21105](https://github.com/brianchandotcom/liferay-portal-ee/pull/21105)

**Pull request closed without merging**
