### PR TITLE
LRQA-75987 | master

### PR DESCRIPTION
**Pull request by lilylcl**
https://issues.liferay.com/browse/LRQA-75987

### CODE REVIEW

**Comment by lilylcl** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
Good job @lilylcl, no changes needed. : )

**Comment by Sharryxue** [comment]
Rebase and resend, refer https://github.com/Sharryxue/liferay-portal/pull/522.

**Pull request closed without merging**
