### PR TITLE
LRQA-74501 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-74501

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed.

**Comment by Sharryxue** [comment]
Rebased and resend [Sharryxue/liferay-portal#396](https://github.com/Sharryxue/liferay-portal/pull/396).

**Pull request closed without merging**
