### PR TITLE
LRQA-62006 | master

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-62006

7.2.x: [brianchandotcom/liferay-portal-ee#31617](https://github.com/brianchandotcom/liferay-portal-ee/pull/31617)
/cc @patriciajeanperez

Thanks

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:stop

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
