### PR TITLE
master-qa-42099

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-42099

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:reopen

**Comment by Songyuewen** [comment]
ci:test

**Comment by liuxingye** [comment]
No test changes needed :)

**Comment by liuxingye** [comment]
Pushed to BChan.
[brianchandotcom#61277](https://github.com/brianchandotcom/liferay-portal/pull/61277).

**Pull request closed without merging**
