### PR TITLE
master-qa-59833

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LRQA-59833
Only commit to the master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Just start reviewing. :)

**Comment by Sharryxue** [comment]
Please resend the fix @chaowang-123, thanks

**Comment by chaowang-123** [comment]
https://issues.liferay.com/browse/LRQA-59833
Only commit to the master.

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Refer [Sharryxue/liferay-portal#192](https://github.com/Sharryxue/liferay-portal/pull/192).

**Pull request closed without merging**
