### PR TITLE
master-qa-42104

### PR DESCRIPTION
**Pull request by HarryC0204**
https://issues.liferay.com/browse/LRQA-42104

### CODE REVIEW

**Comment by HarryC0204** [comment]
ci:test

**Comment by HarryC0204** [comment]
ci:test

**Comment by HarryC0204** [comment]
ci:retest

**Comment by Sharryxue** [comment]
Hello @HarryC0204,
Please remember to resent the PR when you update the origin changes
Wrap the variable if only one function using it
Thanks

**Comment by Sharryxue** [comment]
Pushed to BChan.
[brianchandotcom#61481](https://github.com/brianchandotcom/liferay-portal/pull/61481)
[brianchandotcom#21105](https://github.com/brianchandotcom/liferay-portal-ee/pull/21105)

**Pull request closed without merging**
