### PR TITLE
master-qa-50748

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/LRQA-50748
Submit for master.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed,

**Comment by Sharryxue** [comment]
Rebase and resend [Sharryxue/liferay-portal#379](https://github.com/Sharryxue/liferay-portal/pull/379)

**Pull request closed without merging**
