### PR TITLE
LPS-169946 | master

### PR DESCRIPTION
**Pull request by lilylcl**
https://issues.liferay.com/browse/LPS-169946

### CODE REVIEW

**Comment by lilylcl** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed. :)

**Comment by Sharryxue** [comment]
Rebase and resend, refer https://github.com/Sharryxue/liferay-portal/pull/522.

**Pull request closed without merging**
