### PR TITLE
LRQA-68955

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-68955

Coomits are only for master, thanks.

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test

**Comment by Sharryxue** [comment]
ci:test

**Comment by Sharryxue** [comment]
Hello @patriciajeanperez,
Would you please help with forwarding this pr by removing the commit of [LRQA-68955 Run CI](https://github.com/Sharryxue/liferay-portal/pull/315/commits/ac54e9ae057e32cdbed34c3a39a4a603cc3bc7ca) if the affected tests can be passed in CI? Thanks in advance.

**Comment by patriciajeanperez** [comment]
testing here: https://github.com/patriciajeanperez/liferay-portal/pull/379

I could have used json macros for adding the user and setting the password but you might have intentionally updated it to use the UI, so I fixed the tests to still use the UI @Sharryxue

**Comment by Sharryxue** [comment]
Thanks for updating and forwarding the test @patriciajeanperez

**Pull request closed without merging**
