### PR TITLE
LRQA-75449 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-75449

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
[LRQA-75474](https://issues.liferay.com/browse/LRQA-75474) is created for reverting the workaround changes, please use it in steads. Thanks.

**Review by Sharryxue — CHANGES_REQUESTED** [review]
Hello @melodywu ,
Please use the proper ticket to commit the changes. Thanks.

**Comment by Sharryxue** [comment]
Seems this can be closed since a new pr send in https://github.com/Sharryxue/liferay-portal/pull/468. Would you please double check of it @melodywu, thanks in advance.

**Pull request closed without merging**
