### PR TITLE
LPS-169784 | master

### PR DESCRIPTION
**Pull request by lilylcl**
https://issues.liferay.com/browse/LPS-169784

### CODE REVIEW

**Comment by lilylcl** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed.
Added a refactor issue in LPS-169946 to move the assert success message step out of the macro, and reuse it in another test.

**Comment by Sharryxue** [comment]
Rebase and resend. refer https://github.com/Sharryxue/liferay-portal/pull/508.

**Pull request closed without merging**
