### PR TITLE
LRQA-73700 | master 

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-73700

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed. Thanks
Minor change for the structure, nested the And task into Given block. View [2d4875b](https://github.com/Sharryxue/liferay-portal/pull/359/commits/2d4875b475b88986f718aba7505ab6d78deea039).

**Comment by Sharryxue** [comment]
Resend [Sharryxue/liferay-portal#359](https://github.com/Sharryxue/liferay-portal/pull/359).

**Pull request closed without merging**
