### PR TITLE
master-qa-50468-3

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-50468

Run CI for all affected cases linked on LRQA-50468 with longger pause.

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test

**Comment by Sharryxue** [comment]
ci:test
resolve previous failure by force pushed.

**Comment by patriciajeanperez** [comment]
ci:test

**Comment by patriciajeanperez** [comment]
ci:test

**Comment by patriciajeanperez** [comment]
ci:test

**Comment by Sharryxue** [comment]
Close the outdate pr.

**Pull request closed without merging**
