### PR TITLE
master-qa-45774

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-45774

cc /@GinsonRen

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Hello @Songyuewen ,
I've updated your commit message to reflect this is adding new locator.

**Comment by Sharryxue** [comment]
Pushed to BChan.
[brianchandotcom#66901](https://github.com/brianchandotcom/liferay-portal/pull/66901)

**Pull request closed without merging**
