### PR TITLE
LRQA-68488 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-68488

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:upgrade

**Comment by Sharryxue** [comment]
Just start reviewing.

**Comment by Sharryxue** [comment]
Send with additional commits [liferay-usm/liferay-portal#139](https://github.com/liferay-usm/liferay-portal/pull/139).

**Pull request closed without merging**
