### PR TITLE
master-qa-40314

### PR DESCRIPTION
**Pull request by yunlinsun**
https://issues.liferay.com/browse/LRQA-40314

### CODE REVIEW

**Comment by yunlinsun** [comment]
ci:test:sf

**Comment by yunlinsun** [comment]
ci:test:relevant

**Comment by yunlinsun** [comment]
@GinsonRen @brianwulbern

**Comment by Sharryxue** [comment]
No test changes needed. :)

**Comment by Sharryxue** [comment]
Pushed to BChan.
[brianchandotcom#64738](https://github.com/brianchandotcom/liferay-portal/pull/64738)

**Pull request closed without merging**
