### PR TITLE
LRQA-73353 | LanguageWithOverrideIsBoldWhenFilteringBySpecifiedLanguage | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-73353

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
Changes:
Rename the test and language key value to make it clear, view [2015724](https://github.com/Sharryxue/liferay-portal/pull/405/commits/201572404fe6a0fed252e72b448ed1a08911612d), [5ae42a3](https://github.com/Sharryxue/liferay-portal/pull/405/commits/5ae42a3f31c3c27a179334bad6994a073880244e)

**Comment by Sharryxue** [comment]
Rebase and resend [Sharryxue/liferay-portal#405](https://github.com/Sharryxue/liferay-portal/pull/405).

**Pull request closed without merging**
