### PR TITLE
LRQA-73392 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-73392

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
Just starting review.

**Review by Sharryxue — CHANGES_REQUESTED** [review]
Hello @epark18,
This is more like a test case required in LRQA-75078. Please update the descriptions accordingly. Thanks in advance.

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
Will resend.

**Pull request closed without merging**
