### PR TITLE
LRQA-73526 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-73526

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed. : )

**Comment by Sharryxue** [comment]
Rebase and forwarded.
https://github.com/Sharryxue/liferay-portal/pull/471

**Pull request closed without merging**
