### PR TITLE
master-qa-40812

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-40812

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Songyuewen** [comment]
ci:test

**Comment by Sharryxue** [comment]
Hello @Songyuewen 
- Make sure to create a new pr when you resend the pull
- I've removed several assertPartialText since now the text can be all matched
- For the related asset locator, since there are two related asset link on page, I've updated the locator used in this case more specific. Remember not hard coding the locator if possible
- When updating the locator, try to make it simple and readable and for the locator name, make it as clear as you can
- SF for the variables declaration

**Comment by Sharryxue** [comment]
Pushed to BChan.
[brianchandotcom#59814](https://github.com/brianchandotcom/liferay-portal/pull/59814)

**Pull request closed without merging**
