### PR TITLE
LRQA-50750 | master

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/LRQA-50750
Submit for master.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
Minor change
Shorten the commit message, view [3f37c83](https://github.com/Sharryxue/liferay-portal/pull/405/commits/3f37c8316ffedf1a3865070284910de5cae50fe5).

**Comment by Sharryxue** [comment]
Rebase and resend [Sharryxue/liferay-portal#405](https://github.com/Sharryxue/liferay-portal/pull/405).

**Pull request closed without merging**
