### PR TITLE
LPS-170379 | master

### PR DESCRIPTION
**Pull request by lilylcl**
https://issues.liferay.com/browse/LPS-170379

### CODE REVIEW

**Comment by lilylcl** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed. :)

**Comment by Sharryxue** [comment]
Rebase and resend. Refer https://github.com/Sharryxue/liferay-portal/pull/517.

**Pull request closed without merging**
