### PR TITLE
master-qa-42134

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-42134

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test

**Comment by Sharryxue** [comment]
@Songyuewen
The CI failure not related to this pull.

**Comment by Sharryxue** [comment]
ci:reopen

**Comment by Sharryxue** [comment]
Hello @Songyuewen,
I've updated your commit message.

**Comment by Sharryxue** [comment]
No changes needed. :)

**Comment by Sharryxue** [comment]
Pushed to BChan.
master: [brianchandotcom#61100](https://github.com/brianchandotcom/liferay-portal/pull/61100)
7.1.x: [brianchandotcom#20895](https://github.com/brianchandotcom/liferay-portal-ee/pull/20895)

**Pull request closed without merging**
