### PR TITLE
LRQA-73479, LRQA-72929 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-72929 - Changes made for comment
https://issues.liferay.com/browse/LRQA-73479 Added to do stub

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just start reviewing.

**Comment by Sharryxue** [comment]
No changes needed.

**Comment by Sharryxue** [comment]
Rebase and resend [Sharryxue/liferay-portal#335](https://github.com/Sharryxue/liferay-portal/pull/335)

**Pull request closed without merging**
