### PR TITLE
LRQA-73904 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-73904

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test

**Comment by Sharryxue** [comment]
Hello @melodywu 
Please check and fix the SF issue. Thanks

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
> Hello @melodywu Please check and fix the SF issue. Thanks

Done

**Comment by Sharryxue** [comment]
Thanks for sending the commit, this is duplicated, refer changes [Sharryxue/liferay-portal#343](https://github.com/Sharryxue/liferay-portal/pull/343). Close without review.
/cc @melodywu

**Pull request closed without merging**
