### PR TITLE
LRQA-75716 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-75716

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:usm

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
Minor change in alphabetical the order, view 5a472b54.

**Comment by Sharryxue** [comment]
Rebase and add new commit.
https://github.com/Sharryxue/liferay-portal/pull/443

**Pull request closed without merging**
