### PR TITLE
LRQA-76300 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-76300

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
Made minor change in description and restructure the BDD modal. Refer 184d3d92.

**Comment by Sharryxue** [comment]
Rebase and resend, refer https://github.com/Sharryxue/liferay-portal/pull/510.

**Pull request closed without merging**
