### PR TITLE
master-qa-45763

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-45763

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
No test changes needed. :)

**Comment by Sharryxue** [comment]
Pushed to BChan.
[brianchandotcom/liferay-portal#69173](https://github.com/brianchandotcom/liferay-portal/pull/69173)

**Pull request closed without merging**
