### PR TITLE
LRQA-76171 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-76171

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed. :)

**Comment by Sharryxue** [comment]
Rebase and resend, refer https://github.com/Sharryxue/liferay-portal/pull/460

**Pull request closed without merging**
