### PR TITLE
LRQA-75067 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-75067

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed.

**Comment by Sharryxue** [comment]
Rebase and resend.
[Sharryxue/liferay-portal/411](https://github.com/Sharryxue/liferay-portal/pull/411)

**Pull request closed without merging**
