### PR TITLE
LRQA-73092, LRQA-74202, LPS-150625, LRQA-50759 | master

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-73092
https://issues.liferay.com/browse/LRQA-74202
https://issues.liferay.com/browse/LPS-150625
https://issues.liferay.com/browse/LRQA-50759

/cc @epark18 @melodywu @jaydawu
Commits are only for master, thanks.

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:forward

**Comment by epark18** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:forward

**Comment by Sharryxue** [comment]
ci:forward

**Pull request closed without merging**
