### PR TITLE
LRQA-76234 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-76234
Temporary workaround. At the moment, the InstanceSettings tests that deal with factory configurations are causing failures in many other tests that run in the same batch due to a bad cleanup. Having them run on separate instances allows for our tests within the InstanceSettings testcase to pass. This is being tracked in https://issues.liferay.com/browse/LPS-158349.

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:usm

**Comment by Sharryxue** [comment]
Just starting review.

**Comment by Sharryxue** [comment]
No changes needed. : )

**Comment by Sharryxue** [comment]
ci:forward

**Pull request closed without merging**
